apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nfs/registry
    server: 192.168.2.209
  persistentVolumeReclaimPolicy: Retain
