apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
  selector:
    app: registry
  type: NodePort