---
- name: Configure k3s to use an insecure Docker registry
  hosts: all
  become: yes
  tasks:
    - name: Ensure containerd configuration directory exists
      file:
        path: /etc/rancher/k3s
        state: directory
        mode: '0755'

    - name: Create or update containerd registries configuration
      copy:
        dest: /etc/rancher/k3s/registries.yaml
        content: |
          mirrors:
            "localhost:30007":
              endpoint:
                - "http://localhost:30007"
      notify: Restart k3s

  handlers:
    - name: Restart k3s
      systemd:
        name: k3s
        state: restarted
        enabled: yes
